server {
    listen 80;
    server_name _;

    # Указываем DNS Докера (127.0.0.11), чтобы Nginx не падал при старте, если pocketbase еще не готов
    resolver 127.0.0.11 valid=30s;

    root /usr/share/nginx/html;
    index index.html;

    # Основной сайт (React SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Проксируем запросы к PocketBase REST API
    location /api/ {
        set $pb_api http://pocketbase:8090;
        proxy_pass $pb_api;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Проксируем запросы к админке PocketBase (_/)
    location /_/ {
        set $pb_admin http://pocketbase:8090;
        proxy_pass $pb_admin;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

